---
commitizen:
  bump_message: 'bump(sockutls): $current_version -> $new_version'
  pre_bump_hooks: python ../../ci/changelog.py sock_utils
  tag_format: sock_utils-v$version
  version: 0.1.0
  version_files:
  - idf_component.yml
